# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Date.o main.o struct.o
LINKOBJ  = Date.o main.o struct.o
LIBS     = -L"H:/Programs/Dev-Cpp/MinGW64/lib" -L"H:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"H:/Programs/Dev-Cpp/MinGW64/include" -I"H:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"H:/Programs/Dev-Cpp/MinGW64/include" -I"H:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"H:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Date.o: Date.cpp
	$(CPP) -c Date.cpp -o Date.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

struct.o: struct.cpp
	$(CPP) -c struct.cpp -o struct.o $(CXXFLAGS)
